### ISSUE TITLE
Task 3: Certificate Checks: Priority

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#15]
We will be rolling out the certificate from today, which means we have to make sure everything works properly before rolling it out. 

So, we need to check and report any issues with this comment. 
Dont share details to outside this group.

- [ ] List down any problem you see 
- [ ] If possible suggest solution
- [ ] Then we will try to fix one by one

Certificate link: https://gssoc.girlscript.tech/verify_cert

Github resource: https://github.com/girlscript/gssoc-website-new/tree/main/public/certificates/2024
repo link: https://github.com/girlscript/gssoc-website-new

**Comment by Swarnendu0123** [comment]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/601d3826-bd26-4a16-93c9-acbc43a9a96f">
The certificate itself looks like this. We have to replace the image. That’s it.
Also, the image quality of the certificate is decreased. We can replace all the certificates with new high-quality certificates.

**Comment by vansh-codes** [comment]
- The image quality of the certificate needs to be improved
- `Certificate of appreciation` in place of `Certificate of participation`, needs to be fixed in the template
link: https://github.com/girlscript/gssoc-website-new/blob/main/public/certificates/2024/GSSoC_TopContrib_Cert.png

**Comment by RadhikaMalpani1702** [comment]
Hi @sanjay-kv ,

I’m unable to download my certificate even though I’ve entered my correct details. It shows a verification failed error. My rank is 29th.

This is my email ID: radhikavishnudas2002@gmail.com

Please check on this issue. It seems to be affecting several contributors, especially those who didn’t receive a confirmation email for GSSoC or those who are on the leaderboard due to the Postman challenge.


https://github.com/user-attachments/assets/328c1eeb-8d6e-429f-9c25-f0decca8c881

**Comment by MastanSayyad** [comment]
Hi @sanjay-kv,

The issue found by @RadhikaMalpani1702 is significant. I was sure this might happen. I think We need to add these people's email IDs to the certificate data rendering so they can verify and download their certificates.

The affected groups are:

- Those who did not receive the GSSoC confirmation email
- Those who ranked and had their names on the leaderboard due to the Postman API Challenge

**Comment by vansh-codes** [comment]
> Hi @sanjay-kv ,
> 
> I’m unable to download my certificate even though I’ve entered my correct details. It shows a verification failed error. My rank is 29th.
> 
> This is my email ID: [radhikavishnudas2002@gmail.com](mailto:radhikavishnudas2002@gmail.com)
> 
> Please check on this issue. It seems to be affecting several contributors, especially those who didn’t receive a confirmation email for GSSoC or those who are on the leaderboard due to the Postman challenge.
> 
>  15.08.2024_07.52.43_REC.mp4

Hii @RadhikaMalpani1702 ,
Your verification is failing because your mail id is not mentioned here: 
https://github.com/girlscript/gssoc-website-new/blob/main/public/certificatesData/2024/Top100.json

@sanjay-kv I think some data is wrong in Top100.json file as I can see the emails are mentioned according to rank, but it gets wrong at few places disturbing other datas position as well. For example: Siddheya's rank is 3rd but he is listed 4th in the json file and many more places where the contributors are mentioned in wrong position and only 94 emails are mentioned, 6 are missing. One of those missing email is of @RadhikaMalpani1702 
Please recheck the Top100.json and mention the contributors missed out.

**Comment by RadhikaMalpani1702** [comment]
That's great insight, @vansh-codes  Similarly, the Postman API Challenge participants on the leaderboard might face the same issue.

**Comment by MastanSayyad** [comment]
Yes, @vansh-codes, instead of Sidhheya, Unnimaya is listed. While this might not have a significant impact, the missing emails could definitely cause issues.

**Comment by vansh-codes** [comment]
@MastanSayyad exactly! Also because of wrong ordering now it becomes tough to find those 6 people whose email is not mentioned. It could have been easier if the order was the same as the rank on the leaderboard

**Comment by sanjay-kv** [comment]
@vansh-codes we are creating a new template, I noticed certificate quality is not good. 
https://www.figma.com/design/wlIszNShK2h7rwPpzjuVYq/Certification?node-id=411-3&t=8Zm52qGd91VWxoJq-0

**Comment by sanjay-kv** [comment]
> > Hi @sanjay-kv ,
> > I’m unable to download my certificate even though I’ve entered my correct details. It shows a verification failed error. My rank is 29th.
> > This is my email ID: [radhikavishnudas2002@gmail.com](mailto:radhikavishnudas2002@gmail.com)
> > Please check on this issue. It seems to be affecting several contributors, especially those who didn’t receive a confirmation email for GSSoC or those who are on the leaderboard due to the Postman challenge.
> > 15.08.2024_07.52.43_REC.mp4
> 
> Hii @RadhikaMalpani1702 , Your verification is failing because your mail id is not mentioned here: https://github.com/girlscript/gssoc-website-new/blob/main/public/certificatesData/2024/Top100.json
> 
> @sanjay-kv I think some data is wrong in Top100.json file as I can see the emails are mentioned according to rank, but it gets wrong at few places disturbing other datas position as well. For example: Siddheya's rank is 3rd but he is listed 4th in the json file and many more places where the contributors are mentioned in wrong position and only 94 emails are mentioned, 6 are missing. One of those missing email is of @RadhikaMalpani1702 Please recheck the Top100.json and mention the contributors missed out.

noted.

**Comment by sanjay-kv** [comment]
> @MastanSayyad exactly! Also because of wrong ordering now it becomes tough to find those 6 people whose email is not mentioned. It could have been easier if the order was the same as the rank on the leaderboard

@Hemu21 can you look into this.

**Comment by vansh-codes** [comment]
@sanjay-kv this template looks good and attractive 💥🚀

**Comment by Hemu21** [comment]
You can see the list of missing mails here. https://github.com/GSSoC24/Contributor/discussions/591

**Comment by Hemu21** [comment]
@RadhikaMalpani1702  now you can download your certificate.

**Comment by RadhikaMalpani1702** [comment]
Yeah thank @Hemu21

**Comment by aslams2020** [comment]
Hey @sanjay-kv 

The input box for entries for certificates `Enter registered  email` , `Enter name` is **not visible in light mode**

As you can see here - 
![image](https://github.com/user-attachments/assets/638075ca-147d-4864-bc2a-ad7b0e2db5c8)

User's may tend to get confused where to enter my inputs, I myself got confused earlier..

**Comment by sanjay-kv** [comment]
> Hey @sanjay-kv
> 
> The input box for entries for certificates `Enter registered email` , `Enter name` is **not visible in light mode**
> 
> As you can see here - ![image](https://private-user-images.githubusercontent.com/131389695/358123068-638075ca-147d-4864-bc2a-ad7b0e2db5c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTcyNzcsIm5iZiI6MTcyMzY5Njk3NywicGF0aCI6Ii8xMzEzODk2OTUvMzU4MTIzMDY4LTYzODA3NWNhLTE0N2QtNDg2NC1iYzJhLWFkN2IwZTJkYjVjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDQyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjAxYmM1YmFkYTRjOGFiMTYyNGVmY2U1ZTU5MjM4YzMxNDVkOWViMWFlNmM2YWZkYmMxNWQxMjlhNjk3MWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZroVYvM14uLf_ZEAMQc8FolEDrz9gGeGc_4TcWYbutk)
> 
> User's may tend to get confused where to enter my inputs, I myself got confused earlier..

thanks for highlighting.

**Comment by aslams2020** [comment]
@sanjay-kv 
To emphasize the importance of the "CEO Name" and "Managing Director Name," **we can style these elements in black with bold text.** 
Additionally, **we can use a grey color for their respective titles** **"to distinguish their roles"** in the GirlScript Foundation.

Currently :  
![image](https://github.com/user-attachments/assets/0aa2fdde-c5d0-44d9-9c00-2eb67d7dcac1)

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/ba3f3491-19b3-4937-b2b3-0e4c6a6c9c82)

@sanjay-kv in dark mode when we go to select a field there is no line visible that the field has been selected it can cause some confusion for some people especially the ones who are a bit in hurry 

Even i got confused

only after typing i noticed that the field has been selected in the above image i have selected the email field but as you can see we cant tell if the field has been selected as the white line is right on top of the left side

**Comment by vansh-codes** [comment]
> ![image](https://github.com/user-attachments/assets/ba3f3491-19b3-4937-b2b3-0e4c6a6c9c82)
> 
> @sanjay-kv in dark mode when we go to select a field there is no line visible that the field has been selected it can cause some confusion for some people especially the ones who are a bit in hurry 
> 
> Even i got confused
> 
> only after typing i noticed that the field has been selected in the above image i have selected the email field but as you can see we cant tell if the field has been selected as the white line is right on top of the left side

Hey @aditya-bhaumik 
It's similar to the one told in this https://github.com/GSSoC24/.github/issues/15#issuecomment-2290580953

**Comment by aditya-bhaumik** [comment]
@vansh-codes thats for light mode i checked that comment and wrote here this is for dark mode even the dark mode is facing the same problem
 and dont worry its not a competition if it was same also i dont think there should be a issue

**Comment by vansh-codes** [comment]
@aditya-bhaumik agreed 💯

**Comment by vansh-codes** [comment]
Idea for certificate verification: https://github.com/GSSoC24/.github/discussions/29

**Comment by aditya-bhaumik** [comment]
i think for the certificate verification both mine and vansh's name should be added as he improved the idea which i had given 
in #27

**Comment by MastanSayyad** [comment]
@aditya-bhaumik It will get added, you can ignore the above list it was just a summary for past suggestions

**Comment by sanjay-kv** [comment]
https://drive.google.com/drive/folders/1NhZpRgjQbbP3S_dcWsaGCn43GkCtAGAw?usp=sharing

if anyone free can you replace the existing certificates with these?
https://github.com/girlscript/gssoc-website-new/tree/main/public/certificates/2024
https://github.com/girlscript/gssoc-website-new/commits/main/

**Comment by MastanSayyad** [comment]
Sure @sanjay-kv

**Comment by shreyash3087** [comment]
> Issue mentioned by @ nishatn ![image](https://private-user-images.githubusercontent.com/30715153/358040178-e1d4523e-f40a-462f-aa2c-de5606da8b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTMyNjgsIm5iZiI6MTcyMzcxMjk2OCwicGF0aCI6Ii8zMDcxNTE1My8zNTgwNDAxNzgtZTFkNDUyM2UtZjQwYS00NjJmLWFhMmMtZGU1NjA2ZGE4YjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5MDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlODdiMGJkZDdjNzc5MmQzZGI1YjU3OGFkZmQ1ODY1OTlmMWI2ZGNiNjlkYmFhMTczYmJiMDA3YzMzYWExNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fp69slE0wvmXXJJbBcsKw74MknJ4OhKIpeUw3Z5H-NE)
> 
> mobile download fail:
> 
> Solution: the problem is current code is building one frame in big screen where there is certificate image in background and over that image there is text . which previous contributor has aligned manually so when we click on download so that frame is getting download as it is . which he have handled upto screen width of 1080px .after that the text and image is not handled . +the frame display gets none after 1080px screen so thats why when we try to download certificate its give 0B image (coruptt image) because frame doesnt exist in that device .





i have a solution to this @sanjay-kv ,what we can do is for mobile devices we can make the whole certificate div as absolute and put it out of the screen using `top:10000px` or a very high value or something,instead of making the frame none,this will allow us to get the certificate even in mobile devices,since the frame is not none but just out of the screen. check out this video -

https://github.com/user-attachments/assets/523b87fc-26e6-45e5-b7eb-31d17e8cd216

**Comment by vansh-codes** [comment]
> https://drive.google.com/drive/folders/1NhZpRgjQbbP3S_dcWsaGCn43GkCtAGAw?usp=sharing and do the PR
> @MastanSayyad 
> if anyone free can you replace the existing certificates with these?
> https://github.com/girlscript/gssoc-website-new/tree/main/public/certificates/2024
> https://github.com/girlscript/gssoc-website-new/commits/main/

Hi @sanjay-kv 

https://drive.google.com/file/d/1nNgMMsQhSuay9vrsMstNHnN0IUnWBsfA/view?usp=drivesdk
In this .xyz is not mentioned, please have a look if it's a mistake or been done knowingly..

**Comment by aslams2020** [comment]
Hey @sanjay-kv 
after the new update of certificates 

for Both Contributors and TOP100 , There is "Certificate of Appreciation" 
![image](https://github.com/user-attachments/assets/96f6bd5e-3709-4d60-9f27-8342a7c9931b)

**For Contributors** - It Should be **"Certificate of Participation"**
and
**For Top100 Contributors** - It Should be **"Certificate of Appreaciation"** Which makes those top-performers certificate unique.

**Comment by vansh-codes** [comment]
![Vansh Chaurasiya_Cert_Top Contributor_GSSoC2024 (1)](https://github.com/user-attachments/assets/aa9d34d1-548b-4794-b492-979eafb73c3c)

![image](https://github.com/user-attachments/assets/f80f17e2-9333-4d0f-8ec0-83ab5aee5185)


The position of name and the placeholder `XXXXXXX` is wrong

**Comment by aditya-bhaumik** [comment]
@aslams2020 yes exactly as the only thing extra for 61 to 100 was the certificate of appreciation now if everyone is getting that then there is nothing unique 
before it was mentioned that people who score 60 points will get certificate of participation so many people made only that much score

**Comment by MastanSayyad** [comment]
@vansh-codes Yeah, They are fixing it

**Comment by Ojas-Arora** [comment]
@sanjay-kv Sir for every certificate Certificate Id should be present which would be different for different contributors/mentors/project admin. Right now after generating certificate no Certificate Id is generated.

**Comment by sanjay-kv** [comment]
> Hey @sanjay-kv
> 
> The input box for entries for certificates `Enter registered email` , `Enter name` is **not visible in light mode**
> 
> As you can see here - ![image](https://private-user-images.githubusercontent.com/131389695/358123068-638075ca-147d-4864-bc2a-ad7b0e2db5c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjEzOTgsIm5iZiI6MTcyMzcyMTA5OCwicGF0aCI6Ii8xMzEzODk2OTUvMzU4MTIzMDY4LTYzODA3NWNhLTE0N2QtNDg2NC1iYzJhLWFkN2IwZTJkYjVjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMTI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDkyNGI1NTc2YmIwODQwNDBhNDQ5NjA4ZjEyMWUwMmU5ZjhjZWNmYzk2ZDAyNGFhMjBlNDY3ZGQ0YjAzYTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G9RIU7px_O-csvRdGS5cL6fXWvB-Tj6m0mPVcN4f-gE)
> 
> User's may tend to get confused where to enter my inputs, I myself got confused earlier..

This is fixed ✅✅

**Comment by sanjay-kv** [comment]
> i think for the certificate verification both mine and vansh's name should be added as he improved the idea which i had given in #27

sure

**Comment by shreyash3087** [comment]
> > Issue mentioned by @ nishatn ![image](https://private-user-images.githubusercontent.com/30715153/358040178-e1d4523e-f40a-462f-aa2c-de5606da8b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTMyNjgsIm5iZiI6MTcyMzcxMjk2OCwicGF0aCI6Ii8zMDcxNTE1My8zNTgwNDAxNzgtZTFkNDUyM2UtZjQwYS00NjJmLWFhMmMtZGU1NjA2ZGE4YjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5MDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlODdiMGJkZDdjNzc5MmQzZGI1YjU3OGFkZmQ1ODY1OTlmMWI2ZGNiNjlkYmFhMTczYmJiMDA3YzMzYWExNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fp69slE0wvmXXJJbBcsKw74MknJ4OhKIpeUw3Z5H-NE)
> > mobile download fail:
> > Solution: the problem is current code is building one frame in big screen where there is certificate image in background and over that image there is text . which previous contributor has aligned manually so when we click on download so that frame is getting download as it is . which he have handled upto screen width of 1080px .after that the text and image is not handled . +the frame display gets none after 1080px screen so thats why when we try to download certificate its give 0B image (coruptt image) because frame doesnt exist in that device .
> 
> i have a solution to this @sanjay-kv ,what we can do is for mobile devices we can make the whole certificate div as absolute and put it out of the screen using `top:10000px` or a very high value or something,instead of making the frame none,this will allow us to get the certificate even in mobile devices,since the frame is not none but just out of the screen. check out this video -
> 
>  loom-video.6.mp4

@sanjay-kv check this out

**Comment by sanjay-kv** [comment]
> > https://drive.google.com/drive/folders/1NhZpRgjQbbP3S_dcWsaGCn43GkCtAGAw?usp=sharing and do the PR
> > @MastanSayyad
> > if anyone free can you replace the existing certificates with these?
> > https://github.com/girlscript/gssoc-website-new/tree/main/public/certificates/2024
> > https://github.com/girlscript/gssoc-website-new/commits/main/
> 
> Hi @sanjay-kv
> 
> https://drive.google.com/file/d/1nNgMMsQhSuay9vrsMstNHnN0IUnWBsfA/view?usp=drivesdk In this .xyz and girlscript.tech is not mentioned in the `presented` section, please have a look if it's a mistake or been done knowingly.. ![IMG_20240815_145022.png](https://private-user-images.githubusercontent.com/114163734/358178895-04aaf5a2-fd7a-4812-a7f8-ec8ad0664dc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjEzOTgsIm5iZiI6MTcyMzcyMTA5OCwicGF0aCI6Ii8xMTQxNjM3MzQvMzU4MTc4ODk1LTA0YWFmNWEyLWZkN2EtNDgxMi1hN2Y4LWVjOGFkMDY2NGRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMTI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzBlNTkwZWVjYjgxNDZjODhkMzRiOTcwMTQxNzU0MzcyOWZiYzQ3MTkwOWVhZmY1OGMxNWRkNzhiMDczYjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DQyOfCbgnghwbYWVWahK4ZwSnH4IToXA4Q_N_nxexTc)

https://github.com/GSSoC24/.github/issues/38

raised issue for this
