### ISSUE TITLE
Task 4: Selecting Top 50 Mentors

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#33]
Here is the Link: https://docs.google.com/spreadsheets/d/1JlRewDP9KhUiOy4iuweXygCTWUwzQLHnIuXPqpLZ5zo/edit?usp=sharing

watch the video: https://www.loom.com/share/8cae4640d7ef4365b1e930bb00e3faf1?sid=f4d49a7f-71e4-403d-8c62-66481bb808eb

**Comment by Hemu21** [comment]
[csvjson (1).json](https://github.com/user-attachments/files/16624784/csvjson.1.json)

**Comment by nikki-05** [comment]
@sanjay-kv  sir, can I delete the duplicate rows?

**Comment by sanjay-kv** [comment]
yes,

**Comment by suhanipaliwal** [comment]
[csvjson.1 (1).json](https://github.com/user-attachments/files/16625129/csvjson.1.1.json)
Removed all the duplicates

**Comment by sau-mili** [comment]
@sanjay-kv  should we also add the email ids of the mentors in the sheet 1? in this sheet: https://docs.google.com/spreadsheets/d/1JlRewDP9KhUiOy4iuweXygCTWUwzQLHnIuXPqpLZ5zo/edit?gid=574997560#gid=574997560

**Comment by sanjay-kv** [comment]
yes @sau-mili
