### ISSUE TITLE
Task 5: Selecting the top 50 PA

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#34]
anyone can work on this. 

we look for collaborative work. 

Excel: https://docs.google.com/spreadsheets/d/1J584tTDkcw2aUYt1Ix9dOMNFe42yH2ecx5k5JVrg1uA/edit?usp=sharing

watch video: https://www.loom.com/share/da5355c904514ef0ae6d7aac1b61b60f?sid=2410d26d-5f8a-4a40-825a-612c41509a4d

**Comment by Asymtode712** [comment]
@sanjay-kv I am working on it

**Comment by nishant0708** [comment]
https://docs.google.com/spreadsheets/d/1070xFU6qrghpyFmEVQYmHVX0NI8IIF6GvUySeBjT3hM/edit?usp=sharing

**Comment by anshikatiwari20** [comment]
I am also working on it.

**Comment by vivekv2810** [comment]
i am also working on it

**Comment by nishant0708** [comment]
@anshikatiwari20  @vivekv2810 i guess its completed .Checkout link if you want to add something

**Comment by Asymtode712** [comment]
> @anshikatiwari20 @vivekv2810 i guess its completed .Checkout link if you want to add something

Great work @nishant0708 , just recount the votes for the 1st PA Anishka cause it seems to be 17 but in your sheet its 16 so please recheck it once

**Comment by vivekv2810** [comment]
> @anshikatiwari20 @vivekv2810 i guess its completed .Checkout link if you want to add something

@nishant0708 i think rishit mondal votes count should be 29

**Comment by Asymtode712** [comment]
> > @anshikatiwari20 @vivekv2810 i guess its completed .Checkout link if you want to add something
> 
> @nishant0708 i think rishit mondal votes count should be 29

@vivekv2810 Actually he has removed the duplicate votes, like there are people who have voted for a PA multiple times...so his tally is right

**Comment by vivekv2810** [comment]
> > > @anshikatiwari20 @vivekv2810 i guess its completed .Checkout link if you want to add something
> > 
> > 
> > @nishant0708 i think rishit mondal votes count should be 29
> 
> @vivekv2810 Actually he has removed the duplicate votes, like there are people who have voted for a PA multiple times...so his tally is right

Yes, Got it @Asymtode712

**Comment by vivekv2810** [comment]
means @sanjay-kv i have created another account in github 2 hrs ago

**Comment by sanjay-kv** [comment]
okay
