### ISSUE TITLE
Task 7: Certification not available to certain users

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#37]
Hi 

I’m unable to download my certificate even though I’ve entered my correct details. It shows a verification failed error. My rank is 29th.

This is my email ID: radhikavishnudas2002@gmail.com

Please check on this issue. It seems to be affecting several contributors, especially those who didn’t receive a confirmation email for GSSoC or those who are on the leaderboard due to the Postman challenge.

https://github.com/user-attachments/assets/328c1eeb-8d6e-429f-9c25-f0decca8c881

![image](https://github.com/user-attachments/assets/58827505-50a0-4ac1-a2e9-efe3f465f477)
![image](https://github.com/user-attachments/assets/255203c0-ff0b-4f57-aca7-cfbd760d0af0)
![image](https://github.com/user-attachments/assets/5320b9b5-4648-4570-88b3-1e6d477985f3)
![image](https://github.com/user-attachments/assets/00e42f84-8541-4f90-a1a4-59b999a41a7f)

Solution: 
https://github.com/GSSoC24/Contributor/discussions/591

This is the resource: https://github.com/GSSoC24/.github/discussions/36

**Comment by sanjay-kv** [comment]
dont work on this @Hemu21 is working

**Comment by Hemu21** [comment]
@sanjay-kv  I already added that mail.
