### ISSUE TITLE
Task 8: Replace the top contributor certificate

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#38]
![image](https://github.com/user-attachments/assets/909ed344-bb53-411c-b636-f97ae2ccf81b)
we had this issue on top contributor certificate. 

so I update the image . use the below one, if you need high quality one check this 
https://www.canva.com/design/DAGN6YrhO4M/-WlQ4izXt20ZovFBxBaZMw/edit?utm_content=DAGN6YrhO4M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

![Colorful Modern Geometric Certificate of Participation](https://github.com/user-attachments/assets/ba734b6f-aa8f-446d-ae76-bacd1ceb67f0)

This is where certificate is stored: https://github.com/girlscript/gssoc-website-new/tree/main/public/certificates/2024

**Comment by MastanSayyad** [comment]
@sanjay-kv On it

**Comment by Hemu21** [comment]
done

**Comment by MastanSayyad** [comment]
So you replaced it @Hemu21 I was so unsure why my file merged conflicts and the certificate was already replaced.

**Comment by Hemu21** [comment]
yes i repleaced it
