### ISSUE TITLE
Task 9: Replace contributor certificate

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#39]
![image](https://github.com/user-attachments/assets/a9687a5c-c544-41aa-a095-ce357a8beff4)

I fixed it 
![Contributer_ Certificate (2)](https://github.com/user-attachments/assets/8ada797f-559c-4d06-b73a-2c4e5149e010)

resepective file can be find here
https://github.com/GSSoC24/.github/discussions/36

**Comment by Hemu21** [comment]
done

**Comment by sanjay-kv** [comment]
awesome.
