### ISSUE TITLE
Do the Moderation: On GitHub

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#4]
Where to do: https://github.com/GSSoC24/Contributor/discussions
https://github.com/GSSoC24/Postman-Challenge/discussions

How to do: https://www.loom.com/share/10ad4757f5a24335ae00acb55ff2505c?sid=d3732152-196c-404f-bf63-189b385424dd

**Comment by AKSHITHA-CHILUKA** [comment]
Thank you @sanjay-kv
