### ISSUE TITLE
Task 11:💡Add issued date in the certification

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#41]
### Discussed in https://github.com/GSSoC24/.github/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **Tejashri-Taral** August 15, 2024</sup>
Hey @sanjay-kv ,
We can add a Date of issue: [mon,year]
The date of issue on certificate indicates specific date when certificate was officially awarded

eg. Issued: August 2024</div>

**Comment by Hemu21** [comment]
done

**Comment by suhanipaliwal** [comment]
https://github.com/girlscript/gssoc-website-new/pull/363
done

**Comment by sanjay-kv** [comment]
@Hemu21 could you confirm this been merged before

**Comment by Hemu21** [comment]
@sanjay-kv  no need to merge it. i added code for issue date.

**Comment by sanjay-kv** [comment]
@suhanipaliwal I will be adding points for this
