### ISSUE TITLE
Task 12: matching the PA name with email

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#43]
https://docs.google.com/spreadsheets/d/1J584tTDkcw2aUYt1Ix9dOMNFe42yH2ecx5k5JVrg1uA/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1J584tTDkcw2aUYt1Ix9dOMNFe42yH2ecx5k5JVrg1uA/edit?usp=sharing

[PROJECTS admin.xlsx](https://github.com/user-attachments/files/16624919/PROJECTS.admin.xlsx)
Watch this video: https://www.loom.com/share/bbeb036f4d83415f833e815c8f2d860c?sid=b1499be2-059d-491b-bc4e-14dd106cf1d6

**Comment by akshithachiluka** [comment]
completed this task
