### ISSUE TITLE
Task 13: Mentor name match with PA

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#44]
Mentor list Json 
[Mentor List.json](https://github.com/user-attachments/files/16624980/Mentor.List.json)

https://www.loom.com/share/5bc57468a2e64ee79879ecf053c6bf68?sid=c3363c00-c531-4c6f-b043-9d37b5da5090

Mentor Email: 
[Final Mentors.xlsx](https://github.com/user-attachments/files/16625028/Final.Mentors.xlsx)

**Comment by suhanipaliwal** [comment]
[email.json](https://github.com/user-attachments/files/16625556/email.json)
Added emails of the mentors

**Comment by aditya-bhaumik** [comment]
@suhanipaliwal we are working on the list in the google sheet there are many who were pa there and also duplicate values

You can help there if you like
the link is there above

**Comment by Asymtode712** [comment]
@sanjay-kv I was talking bout this issue...
