### ISSUE TITLE
Any Suggestion on the newsletter?

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#47]
What you suggest include top 50 , PA , Mentor and CA on this list. 

![screencapture-gssoc-substack-publish-post-147742428-2024-08-15-23_59_09](https://github.com/user-attachments/assets/1e17c23a-a5ae-4e97-8ce3-f1d96dbc987a)

[screencapture-gssoc-substack-publish-post-147742428-2024-08-15-23_38_28.pdf](https://github.com/user-attachments/files/16625702/screencapture-gssoc-substack-publish-post-147742428-2024-08-15-23_38_28.pdf)

**Comment by sau-mili** [comment]
Looks good, we can add the GSSOC logo below your undersign I guess, Will make it more professional?

**Comment by vansh-codes** [comment]
Looks good! 🚀

**Comment by vivekv2810** [comment]
as @vansh-codes mentioned, it looks good to me also.

**Comment by aditya-bhaumik** [comment]
@sanjay-kv i think we can mention the mentor list but the list has not touched 25 till now

**Comment by RadhikaMalpani1702** [comment]
@sanjay-kv It looks great! Finally, The certification will be rolled out soon. 🎉

**Comment by Meetjain1** [comment]
@sanjay-kv Looks good can we also add our next program details that is winter of blockchain like "what next" then we can add just a little about WOB ?

**Comment by shreyash3087** [comment]
@sanjay-kv looks great

**Comment by SuhainaFathimaM** [comment]
@sanjay-kv It looks great!
