### ISSUE TITLE
Final List

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#49]
Mentor: https://docs.google.com/spreadsheets/d/1JlRewDP9KhUiOy4iuweXygCTWUwzQLHnIuXPqpLZ5zo/edit?gid=574997560#gid=574997560<br>
https://github.com/GSSoC24/alumni/discussions/3

PA: https://docs.google.com/spreadsheets/d/1J584tTDkcw2aUYt1Ix9dOMNFe42yH2ecx5k5JVrg1uA/edit?gid=486057329#gid=486057329<br>
https://github.com/GSSoC24/alumni/discussions/4

CA: https://docs.google.com/spreadsheets/d/1upjyF-pyYxy2eMk0_H2xwFHg9HRZMBxDqIaiM5M-w20/edit?gid=0#gid=0<br>
https://github.com/GSSoC24/alumni/discussions/5

Contributor: https://docs.google.com/spreadsheets/d/1npKU1p5M9OqS92K0e1It0qJM5CF6cYIxBmlY9AANyQA/edit?usp=sharing
https://github.com/GSSoC24/alumni/discussions/6

**Comment by aditya-bhaumik** [comment]
@sanjay-kv okay working on it

**Comment by aditya-bhaumik** [comment]
https://docs.google.com/spreadsheets/d/1npKU1p5M9OqS92K0e1It0qJM5CF6cYIxBmlY9AANyQA/edit?gid=0#gid=0

**Comment by aditya-bhaumik** [comment]
@sanjay-kv done
