### ISSUE TITLE
Task 16: Update the certificate

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#53]
We need to update the certificate. 

replace the contributor certificate the old one has spelling mistake. 
![Contributer_ Certificate (3)](https://github.com/user-attachments/assets/2898c236-1bdf-473a-826b-23041a92553a)
Repo Link: https://github.com/girlscript/gssoc-website-new

Certificate link: https://github.com/girlscript/gssoc-website-new/tree/main/public/certificates/2024

**Comment by Hemu21** [comment]
Done
