### ISSUE TITLE
Task 17: Postman Ideas 

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#54]
https://github.com/GSSoC24/Postman-Challenge

Watch the video: https://www.loom.com/share/330eada855be4fa08a3b8cd992559d31?sid=fdeec1b5-117b-4aaf-a526-557ea87a9290

give your ideas here https://github.com/GSSoC24/.github/discussions: 
Then we will upvote and have discussion just like we did before.

![WhatsApp Image 2024-07-24 at 00 30 22_5e2ea5ff](https://github.com/user-attachments/assets/0d0b9637-224b-4e3d-ad5b-a55f3c0a13f5)

Social media is Twitter Post swags: which is only a Tshirt 
Student Expert Kit is the : Linkidein swags: which is 5 items.

**Comment by sanjay-kv** [comment]
so we have given : Social media kit : 20
Student Expert: 40

**Comment by akshithachiluka** [comment]
#58

**Comment by SuhainaFathimaM** [comment]
Check it out #59

 https://github.com/GSSoC24/.github/discussions/59#discussion-7060614

**Comment by vansh-codes** [comment]
Here's my idea @sanjay-kv 
https://github.com/GSSoC24/.github/discussions/60

**Comment by aditya-bhaumik** [comment]
#63

**Comment by suhanipaliwal** [comment]
My idea: https://github.com/GSSoC24/.github/discussions/66

**Comment by Meetjain1** [comment]
My Idea #73

**Comment by sanjay-kv** [comment]
Its impressive without any further info you guys following standards such as referring to the discussion by hashing

**Comment by mili-7** [comment]
check #78

**Comment by Saumili** [comment]
I have added my idea again, since I got suspended from my two accounts. #88
