### ISSUE TITLE
Bring in More Ideas

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#7]
https://github.com/GSSoC24/.github/discussions

**Comment by vansh-codes** [comment]
Posted a new idea on discussions
Here's the link: https://github.com/GSSoC24/.github/discussions/9

**Comment by shreyash3087** [comment]
I had an idea as well - https://github.com/GSSoC24/.github/discussions/11

would love to know everyone's thought on this

**Comment by vansh-codes** [comment]
New idea: https://github.com/GSSoC24/.github/discussions/13

Looking forward for everyone's opinion and response

**Comment by shreyash3087** [comment]
Have a look at this as well- https://github.com/GSSoC24/.github/discussions/14

**Comment by sanjay-kv** [comment]
awesome, i will review this

**Comment by sau-mili** [comment]
Have a look at #46
