### ISSUE TITLE
Task 18: Winner Poster: Postman batch 3 Linkedin winners

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#70]
Design a poster to post this. 
Make sure you follow postman brand guidelines while preparing

all can create their poster and paste the link below we will post the best one

![image](https://github.com/user-attachments/assets/aed10eb8-349d-4602-a43f-4141f84e62fa)

**Comment by akshithachiluka** [comment]
![Blue and Yellow Minimalist Giveaway Winner Facebook Post](https://github.com/user-attachments/assets/b0b4af9b-208f-4f6f-af9a-cacab2148189)

**Comment by shreyash3087** [comment]
@sanjay-kv How about this - 

![1](https://github.com/user-attachments/assets/094818fa-ede0-4cbf-a8ff-87fe4d104ef9)
![2](https://github.com/user-attachments/assets/6d936266-6e63-429e-bbee-30f3fa56d529)

**Comment by akshithachiluka** [comment]
> @sanjay-kv How about this -
> 
> ![1](https://private-user-images.githubusercontent.com/72603662/358686651-c5bcc7aa-41b6-404f-be40-e35e0e1582de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzU5NzIsIm5iZiI6MTcyMzgzNTY3MiwicGF0aCI6Ii83MjYwMzY2Mi8zNTg2ODY2NTEtYzViY2M3YWEtNDFiNi00MDRmLWJlNDAtZTM1ZTBlMTU4MmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE5MTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmN2VjZWUyMDYwNGMzYjcyZDE1Y2VjMjA3ODk1NTVjOTkxM2UyODZkYmJlYjNiNGQ5NjllM2E5YTZhNDk5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.313JwcDwYdfuU6SdwfFRRzRLHH8vO09qcsR3guLRwkg)

U MISSED SOME NAMES

**Comment by shreyash3087** [comment]
> > @sanjay-kv How about this -
> > ![1](https://private-user-images.githubusercontent.com/72603662/358686651-c5bcc7aa-41b6-404f-be40-e35e0e1582de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzU5NzIsIm5iZiI6MTcyMzgzNTY3MiwicGF0aCI6Ii83MjYwMzY2Mi8zNTg2ODY2NTEtYzViY2M3YWEtNDFiNi00MDRmLWJlNDAtZTM1ZTBlMTU4MmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE5MTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmN2VjZWUyMDYwNGMzYjcyZDE1Y2VjMjA3ODk1NTVjOTkxM2UyODZkYmJlYjNiNGQ5NjllM2E5YTZhNDk5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.313JwcDwYdfuU6SdwfFRRzRLHH8vO09qcsR3guLRwkg)
> 
> U missed some names total 25 winners are there

thankyou wil update it

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/fd66d3dd-c5d6-478e-adbe-ac53e5d10a23)

**Comment by suhanipaliwal** [comment]
![GIVEA](https://github.com/user-attachments/assets/374e82e0-795b-4a41-9c2e-d59041738f16)

**Comment by MastanSayyad** [comment]
Hi @sanjay-kv. I have designed the Poster For **Postman Batch 3 Winners**:


![Postman Winners](https://github.com/user-attachments/assets/862d1b80-8e94-4b5a-a1aa-5421082306cc)


Thank You!

**Comment by suhanipaliwal** [comment]
![GIVEA (1)](https://github.com/user-attachments/assets/1e09a4da-04c8-45cb-9769-90d9c8bd53a1)
Here's my design

**Comment by suhanipaliwal** [comment]
![GIVEA (1)](https://github.com/user-attachments/assets/0f6023b0-9637-406a-b567-6f035a69f44e)
Here's my design

**Comment by sanjay-kv** [comment]
> Hi @sanjay-kv. I have designed the Poster For **Postman Batch 3 Winners**:
> 
> ![Postman Winners](https://private-user-images.githubusercontent.com/101971980/358739986-862d1b80-8e94-4b5a-a1aa-5421082306cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDc5NjUsIm5iZiI6MTcyMzkwNzY2NSwicGF0aCI6Ii8xMDE5NzE5ODAvMzU4NzM5OTg2LTg2MmQxYjgwLThlOTQtNGI1YS1hMWFhLTU0MjEwODIzMDZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNTE0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjgyMWRlNWEzZGU2MzI5MGU4ZGE1YzcxYzQ1MDg4NDI2NDY0N2NkYjczYTRlNzZiOTRlNzU4YzE5MTcwYmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNncoSWTZajf0U173T1gxtyAL4xJ9YguSSwtND46D0Q)
> 
> Thank You!

I used this for linkedin

**Comment by sanjay-kv** [comment]
> @sanjay-kv How about this -
> 
> ![Brown and White Abstract Giveaway Winners Announcement Instagram Post](https://private-user-images.githubusercontent.com/72603662/358694793-a8a2f67f-cf96-4102-88a5-10361d804bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDc5NjUsIm5iZiI6MTcyMzkwNzY2NSwicGF0aCI6Ii83MjYwMzY2Mi8zNTg2OTQ3OTMtYThhMmY2N2YtY2Y5Ni00MTAyLTg4YTUtMTAzNjFkODA0YmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE1MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NGM3ZmM2MTdiNTg4YTQxZDZlOWM0MzQ4NDg2NDU4NWU1NTFiMmQwZGJiNTViNWVjMDJkNjBlYmEwZmM0MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Paj_Bcq2InQuseFOp3xyCiAbdmLj1VNw7zG-AO7xHs)

I will use this for newsletter

**Comment by sanjay-kv** [comment]
@MastanSayyad @shreyash3087 
I slected your posters for newsletter and Linkedin. 

@suhanipaliwal @akshithachiluka @aditya-bhaumik i will roll out your design in upcoming newsletters. Thanks . 
all of your design just look awesome.

**Comment by akshithachiluka** [comment]
> @MastanSayyad @shreyash3087 I slected your posters for newsletter and Linkedin.
> 
> @suhanipaliwal @akshithachiluka @aditya-bhaumik i will roll out your design in upcoming newsletters. Thanks . all of your design just look awesome.

Thank you @sanjay-kv
