### ISSUE TITLE
Task 19: Make Feedback form poster Mentor

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#71]
bring in your ideas.
as mentioned before everyone can bring and make their own poster we can choose the best one and poster. 
every contribution will be rewarded

![2024-08-10_2-50-40](https://github.com/user-attachments/assets/8366d697-b5ce-4935-9a59-4ce7ff707642)

https://docs.google.com/spreadsheets/d/1t_4xQAzYb4_7JTcb3HjwoUoyVAp1w5XeadU6Llt2Wxk/edit?usp=sharing
![GS_logo_Black (1)](https://github.com/user-attachments/assets/b26b86f5-c08d-40e0-af56-533dcd8765ac)
![2024-04-29_22-55-56-removebg-previewfb](https://github.com/user-attachments/assets/dc804932-d1a2-491d-b4e7-a260c183b6dd)
![girlscriptsoc_logo-removebg-preview](https://github.com/user-attachments/assets/c9939214-6104-42c2-9c63-a96a97235ef2)

**Comment by akshithachiluka** [comment]
![Yellow And Black Customer Testimonial Facebook Post](https://github.com/user-attachments/assets/44ee2d49-5fdc-4153-81c7-911628f6cc2a)

**Comment by akshithachiluka** [comment]
If this is fine i will do for all the feedbacks

**Comment by mili-7** [comment]
![feedback postergssoc-01](https://github.com/user-attachments/assets/d61485f9-c860-4714-8ebf-4e16ad867924)
Here you go, First draft.
@sanjay-kv

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/b814769b-9d84-4d72-8006-e53a06d4f9f3)
@sanjay-kv took some time but finally done with this 

How is this i did not add the ones having negative feedback and the ones like good and awesome

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/566bfec5-5787-465e-a183-c38d99b47a0a)
not sure with logo but here is another with the logo

**Comment by shreyash3087** [comment]
@sanjay-kv  How does this look?

![Mentor Review](https://github.com/user-attachments/assets/bc9ab490-d290-4cc6-a9f8-18b5c2dee1dd)

**Comment by sanjay-kv** [comment]
> ![feedback postergssoc-01](https://private-user-images.githubusercontent.com/178566389/358699972-d61485f9-c860-4714-8ebf-4e16ad867924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjI2MTksIm5iZiI6MTcyMzg2MjMxOSwicGF0aCI6Ii8xNzg1NjYzODkvMzU4Njk5OTcyLWQ2MTQ4NWY5LWM4NjAtNDcxNC04ZWJmLTRlMTZhZDg2NzkyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMjM4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTIzOTllYWNiNTdiMmY0MmUwMDc4YTAzNDUwNDk3Y2ZkNmZmYmRkOGRlYTBjODI3MjIxNzFiNWNlNTFiN2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XH4aQwNrp-G-6sOKny021raVvjqot6J0CHcNNB1UWqY) Here you go, First draft. @sanjay-kv

we can use this

**Comment by suhanipaliwal** [comment]
![Your paragraph text](https://github.com/user-attachments/assets/c8add858-e151-47cd-895d-77be45e6af7b)

**Comment by suhanipaliwal** [comment]
![Your paragraph text (1)](https://github.com/user-attachments/assets/4dd48716-30a4-4e7f-ba4e-68c3a4e575ee)

**Comment by sanjay-kv** [comment]
completed
