### ISSUE TITLE
Task 20: Make Feedback  poster from contributor

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#75]
you can create a feedback poster with your image and name just like task 18

we will publish this on socials

**Comment by akshithachiluka** [comment]
![contru=ibutor](https://github.com/user-attachments/assets/46f7c2ad-52a5-4e24-be48-d9e0c5efefcc)

**Comment by akshithachiluka** [comment]
![Red Cream and Yellow Customer Feedback Review Instagram Post (3)](https://github.com/user-attachments/assets/fb819a62-ef11-4c3b-a525-bb7f5a60c2fa)

**Comment by suhanipaliwal** [comment]
![Your paragraph text (2)](https://github.com/user-attachments/assets/db369469-bd24-4145-9bc1-b9b08c94a1f4)

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/486ca2ae-b079-4665-88ba-f1e74be99eaf)

**Comment by anshikatiwari20** [comment]
![Uploading 1.png…]()

**Comment by anshikatiwari20** [comment]
![1](https://github.com/user-attachments/assets/427ec9a1-1990-4165-939c-314bbbc39868)

**Comment by vivekv2810** [comment]
![image](https://github.com/user-attachments/assets/d7243414-f859-4939-b4d5-638dd2a160b5)

**Comment by anshikatiwari20** [comment]
![Feedback2](https://github.com/user-attachments/assets/5a587e91-be25-4832-97f7-4b034d02d4bb)

**Comment by vansh-codes** [comment]
![IMG-20240818-WA0006.jpg](https://github.com/user-attachments/assets/e44fc70c-106a-4bcf-9ef0-a8505e8c499a)

Here's mine  ⭐⭐ ⭐ ⭐ ⭐

**Comment by shreyash3087** [comment]
@sanjay-kv  Mine and thankyou from the bottom of my heart for hosting such an amazing event,GSSoC truely changed a lot of things for me, i started with the basic knowledge about web dev and learnt so much in these 3 months, i wasnt even ready at first to join,was just like what would even happen,but now i think it was one of the best decision for me to join GSSoC, Thanks .



![Screenshot (516)](https://github.com/user-attachments/assets/7c1a27bc-d3eb-4a03-a2d1-930a86288881)

**Comment by mili-7** [comment]
Here's mine @sanjay-kv 
![Feedback-saumili-01](https://github.com/user-attachments/assets/fb9892aa-726b-4a73-b52d-44697cc1618a)

**Comment by sanjay-kv** [comment]
> Here's mine @sanjay-kv ![Feedback-saumili-01](https://private-user-images.githubusercontent.com/178566389/358872478-fb9892aa-726b-4a73-b52d-44697cc1618a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDM2MDgsIm5iZiI6MTcyMzk0MzMwOCwicGF0aCI6Ii8xNzg1NjYzODkvMzU4ODcyNDc4LWZiOTg5MmFhLTcyNmItNGE3My1iNTJkLTQ0Njk3Y2MxNjE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwMTA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMThkNGUyMGMzMjc4NWE3ZmJkNzEzNWMwOTE4NzUxYjhhNzIyMTRmNTkyM2Q5MDYyNDYyMDYzYmVhN2EwMTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NnfLWxVR3qqpPKoV4_3nw1lKfYi6vKs_vPorQ_pfp4E)

Love this design

**Comment by sanjay-kv** [comment]
> Here's mine ⭐⭐ ⭐ ⭐ ⭐ Thank you to GSSOC and specially to @sanjay-kv for being such a great Program Manager ❤️ The GSSOC journey has been incredible for me! Alot of things has changed after participating in GSSoC. From mobiles 8-10hr screentime (by doing timepass) to 8-10hrs of laptop screentime contributing and learning everyday and still now by getting a chance to work together! I believe you are truly a game changer for not only me but for all of us. Your support and passion to help everyone learn and grow is incredible! Thank you so much @sanjay-kv for all what you are doing for us , it really means alot! 🤝
> 
> ## Draft 1
> ![IMG-20240818-WA0006.jpg](https://private-user-images.githubusercontent.com/114163734/358868523-e44fc70c-106a-4bcf-9ef0-a8505e8c499a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDM2MDgsIm5iZiI6MTcyMzk0MzMwOCwicGF0aCI6Ii8xMTQxNjM3MzQvMzU4ODY4NTIzLWU0NGZjNzBjLTEwNmEtNGJjZi05ZWYwLWE4NTA1ZThjNDk5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwMTA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTAxYjdkYjJhNGE3ZDZkYjNjMWVmODRkNjYyMmRlMzRmYWFlOGExMzE0YzM1ZjY4YTJkOTUzYTY4OGUyZTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z2yFnI1LUVddYo-_Na1_QsNCkExjba87ZximZt9PomI)
> 
> ## Draft 2
> ![IMG-20240818-WA0007.jpg](https://private-user-images.githubusercontent.com/114163734/358868760-9fba5fa9-a0e0-43c9-b270-30452dfbb4cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDM2MDgsIm5iZiI6MTcyMzk0MzMwOCwicGF0aCI6Ii8xMTQxNjM3MzQvMzU4ODY4NzYwLTlmYmE1ZmE5LWEwZTAtNDNjOS1iMjcwLTMwNDUyZGZiYjRjZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwMTA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTgxNzk2MzA1ZjRjNGQ0ZDkxNTg2OGZhZGIwZWJhOTliNjkxM2NkYmVlYTNkNjU3M2RhYmYzNmMyZDEyOWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NFOjMOdb-kNfPN7-d4P1AhUEj1H5A4nJnnHmU9q5k7o)

these will go to our website soon

**Comment by akshithachiluka** [comment]
![Copy of canva pa feedback](https://github.com/user-attachments/assets/7d369a74-334c-46b4-aab7-ea2b5f1eee69)

**Comment by akshithachiluka** [comment]
![Copy of canva pa feedback (1)](https://github.com/user-attachments/assets/4a5e59bc-b744-42dd-9453-e007e5ee57b0)

**Comment by akshithachiluka** [comment]
![Copy of canva pa feedback (2)](https://github.com/user-attachments/assets/83795034-809b-44e3-8b6e-340d131ae152)

**Comment by Tejashri-Taral** [comment]
@sanjay-kv ,
Here's mine
![Feedback](https://github.com/user-attachments/assets/482ea501-c49b-490a-934c-0124054cb8b2)

**Comment by Tejashri-Taral** [comment]
Hey @sanjay-kv,
Here's mine
![Feedbak](https://github.com/user-attachments/assets/dc538532-4f8f-451e-9178-6aef34a782ff)

**Comment by aslams2020** [comment]
Hey @sanjay-kv 
Here's My Contributor Feedback Design - 

![ContributorFeedback](https://github.com/user-attachments/assets/cb01b8c2-3ddf-45b6-b3ec-d5835170d2a3)

**Comment by RadhikaMalpani1702** [comment]
![Contributor.png](https://github.com/user-attachments/assets/fb06b00f-60f1-463f-b2e6-185f8cf49233)

**Comment by GarimaSingh0109** [comment]
@sanjay-kv  This is my design.


![Garima Singh](https://github.com/user-attachments/assets/f7dfc1aa-c2d2-47db-a319-5ff4b859c8ec)

**Comment by Saumili** [comment]
![Feedback-saumili-01](https://github.com/user-attachments/assets/07460524-5b70-4638-ba01-9d1f7a4f702f)

**Comment by sanjay-kv** [comment]
can you share this template link, so good.

**Comment by Meetjain1** [comment]
![Copy of Brown Illustration Hiring Instagram Post](https://github.com/user-attachments/assets/228c5dd5-8af6-4b70-af5e-43ad0ec0c83a)

**Comment by sanjay-kv** [comment]
completed
