### ISSUE TITLE
Task 21: Make Feedback poster from Mentor

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#76]
reach out to mentor, and ask for feedback create similar poster like task 18, 19

**Comment by akshithachiluka** [comment]
![Red Cream and Yellow Customer Feedback Review Instagram Post (4)](https://github.com/user-attachments/assets/595e186b-768a-4ca1-9dc2-1c7badf83bb7)

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/b057e6bb-b990-44ee-ae85-986c547fdf64)
@sanjay-kv done

**Comment by suhanipaliwal** [comment]
![mentor](https://github.com/user-attachments/assets/83247898-da94-4b82-a640-291668dacc15)

**Comment by akshithachiluka** [comment]
> ![mentor](https://private-user-images.githubusercontent.com/161575955/358865027-83247898-da94-4b82-a640-291668dacc15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjA5ODMsIm5iZiI6MTcyMzk2MDY4MywicGF0aCI6Ii8xNjE1NzU5NTUvMzU4ODY1MDI3LTgzMjQ3ODk4LWRhOTQtNGI4Mi1hNjQwLTI5MTY2OGRhY2MxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTU4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzI1NTg4MjJkN2U1MmMxNmY1ODhhM2FlNjBlZGViZTBiZWY2MWMxNWRlYjE1ZWMzZDMxMzE0MjFmNWQ3NjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IqUQKLFsXlXfwvXaMUm4xlhxgDq1-mLd6xE7XOK0NkE)

can you send the link of the templet

**Comment by akshithachiluka** [comment]
![Copy of canva pa feedback (3)](https://github.com/user-attachments/assets/ca8bf8fe-8a0b-433a-9ab8-dc024c8cd0a2)

**Comment by shreyash3087** [comment]
![Screenshot (520)](https://github.com/user-attachments/assets/dbbc2dd5-7cc8-453a-883f-f3f9b31a6279)

**Comment by sanjay-kv** [comment]
> ![Screenshot (520)](https://private-user-images.githubusercontent.com/72603662/358889721-dbbc2dd5-7cc8-453a-883f-f3f9b31a6279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5Njc4MjIsIm5iZiI6MTcyMzk2NzUyMiwicGF0aCI6Ii83MjYwMzY2Mi8zNTg4ODk3MjEtZGJiYzJkZDUtN2NjOC00NTNhLTg4M2YtZjNmOWIzMWE2Mjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ODIxZGU0YTA4NjQxZTY0M2ZiNTQ3YWU1MmE2OGZlODFmMjNmNGJmNWJlNjFkMDVjNzU4ZGI0MzQ4NWU2ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ipP1EDF-vd53Q6vIxzl-XUG3IrLjzc5jJmgalsXK3NM)

@shreyash3087 if the mentor thing is not overlaying it would be good. you can bring it down.

**Comment by shreyash3087** [comment]
@sanjay-kv Alright - 

![Screenshot (521)](https://github.com/user-attachments/assets/55d83939-08a3-4af0-96f4-62865f942ce1)

**Comment by mili-7** [comment]
![mentor-feedback-01](https://github.com/user-attachments/assets/f241c4b2-4616-47cf-8eed-1b861fc1332e)

Here's one @sanjay-kv

**Comment by suhanipaliwal** [comment]
![canva pa feedback (1)](https://github.com/user-attachments/assets/13d98a61-6659-4806-ae09-0da8212bff13)

**Comment by suhanipaliwal** [comment]
![canva pa feedback](https://github.com/user-attachments/assets/b5862fb2-5ca5-447e-8a02-e72b116d0642)

**Comment by Saumili** [comment]
![mentor-feedback-01](https://github.com/user-attachments/assets/cebea5eb-de13-4120-a7e3-c43f5e8731df)

**Comment by vivekv2810** [comment]
![image](https://github.com/user-attachments/assets/5076c737-5e5a-4275-a448-55c9ebdebef1)

**Comment by Meetjain1** [comment]
![Copy of Brown Illustration Hiring Instagram Post (2)](https://github.com/user-attachments/assets/94ca356f-638b-4a08-bc8a-7bc2a161840c)

**Comment by suhanipaliwal** [comment]
![canva mentor feedback](https://github.com/user-attachments/assets/cefc49eb-a5d5-4466-ba3a-17de18111cf9)

**Comment by vivekv2810** [comment]
![image](https://github.com/user-attachments/assets/c3608045-a2c7-449c-b494-28138995d184)

**Comment by sanjay-kv** [comment]
completed
