### ISSUE TITLE
Task 22: Make Feedback poster from PA

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#77]
reach out to PA, and ask for feedback create similar poster like task 18, 19

**Comment by akshithachiluka** [comment]
![Red Cream and Yellow Customer Feedback Review Instagram Post (1)](https://github.com/user-attachments/assets/f8d0a99e-2ff2-4dc1-8a7d-6c8307a4524f)

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/c70eacd4-4653-431d-b5fa-1fbeb98eb0ab)

**Comment by suhanipaliwal** [comment]
![mentor (1)](https://github.com/user-attachments/assets/15018529-a3fb-4c6c-9bfd-818885c870de)

**Comment by aditya-bhaumik** [comment]
@suhanipaliwal wasn't the task the contact new project admin and make a poster using their feedback

**Comment by mili-7** [comment]
![PA Feedback-01](https://github.com/user-attachments/assets/2b47a7cb-2942-425a-b2e2-393dc90f235c)

Here's one @sanjay-kv . Should I reach out to more PAs?

**Comment by suhanipaliwal** [comment]
> @suhanipaliwal wasn't the task to contact new project admin and make a poster using their feedback

Oh okay, I'll contact some new project admin

**Comment by shreyash3087** [comment]
@sanjay-kv How's this - 

![Screenshot (512)](https://github.com/user-attachments/assets/2704687d-4fbf-4984-a149-b9e45a1a899b)

**Comment by suhanipaliwal** [comment]
![canva pa feedback](https://github.com/user-attachments/assets/b21f1c32-ae49-4888-8f1e-d9c15d7f37bd)

**Comment by akshithachiluka** [comment]
> ![PA Feedback-01](https://private-user-images.githubusercontent.com/178566389/358866855-2b47a7cb-2942-425a-b2e2-393dc90f235c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjM5NzEsIm5iZiI6MTcyMzk2MzY3MSwicGF0aCI6Ii8xNzg1NjYzODkvMzU4ODY2ODU1LTJiNDdhN2NiLTI5NDItNDI1YS1iMmUyLTM5M2RjOTBmMjM1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNjQ3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZThmYjYwOTgzMzc5NmE3OGViM2ZhNzk4YzI1ZTdhNjdjNDg5MmU1N2M4YWMxOWI3MDJmODczZjdkMjk3Y2U1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YX6j4km_IgNW9h2YW4K0zYk8dMyxkR24L557Ejs_WKw)
> 
> Here's one @sanjay-kv . Should I reach out to more PAs?

send the link of canva template foe this please

**Comment by RadhikaMalpani1702** [comment]
![Project Admin.png](https://github.com/user-attachments/assets/736fe44e-21d9-4421-8ba4-49c789452c8d)

**Comment by Saumili** [comment]
![PA Feedback-01](https://github.com/user-attachments/assets/ab136deb-14d0-4949-93fd-da159c5e3e15)
posting again, got suspended

**Comment by vivekv2810** [comment]
![image](https://github.com/user-attachments/assets/cf160d11-09d2-48a0-a9ec-6087dea6633d)

**Comment by Meetjain1** [comment]
![Copy of Brown Illustration Hiring Instagram Post (3)](https://github.com/user-attachments/assets/3ab9e443-d223-418c-9384-e9537204df0e)

**Comment by vivekv2810** [comment]
![Screenshot 2024-08-20 221435](https://github.com/user-attachments/assets/1af18929-7c91-441f-8394-5e17e3eb7c3a)

**Comment by nikki-05** [comment]
![Screenshot 2024-08-20 234624](https://github.com/user-attachments/assets/84a5263f-6acc-4f3c-81cd-d95b52f4213f)

**Comment by Meetjain1** [comment]
![Copy of Brown Illustration Hiring Instagram Post (5)](https://github.com/user-attachments/assets/180d421e-e27e-4072-a773-b6fdb9e2f6bf)

**Comment by Meetjain1** [comment]
![Copy of Brown Illustration Hiring Instagram Post (6)](https://github.com/user-attachments/assets/358d2f2a-f126-45b6-9be7-30777633aeeb)

**Comment by suhanipaliwal** [comment]
![mentor3 feedback (1)](https://github.com/user-attachments/assets/5d11bdd1-c6fe-4090-a18a-6fca250c3af6)
