### ISSUE TITLE
Task 23 Top 10 contributor : Winner posters with their photo

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#80]
Top 10 : Winner posters with their photo

**Comment by aditya-bhaumik** [comment]
![WhatsApp Image 2024-08-18 at 19 27 03_503139ce](https://github.com/user-attachments/assets/cb4da54c-578a-4faa-aada-7b84b65f56ac)
rank 1 

![WhatsApp Image 2024-08-18 at 19 27 03_05abadbf](https://github.com/user-attachments/assets/39d63984-2f11-499a-9c7e-2f213bfa9960)
rank 2

![WhatsApp Image 2024-08-18 at 19 27 04_6eacf821](https://github.com/user-attachments/assets/8577674c-6bcd-421b-883a-fb47fb4c6b11)
rank 3

![WhatsApp Image 2024-08-18 at 19 27 03_3493039d](https://github.com/user-attachments/assets/22d2adf7-468a-4d3f-9fea-685ec993bd79)

Rank 4

![WhatsApp Image 2024-08-18 at 19 27 04_35013918](https://github.com/user-attachments/assets/5dc16fe8-1fad-42fc-81ee-41ba89e84f0d)

Rank 5 

![WhatsApp Image 2024-08-18 at 19 27 04_50bcedd8](https://github.com/user-attachments/assets/5dcc6066-32cb-4fd4-9fa2-47b7a3b1b4f5)

Rank 6

![WhatsApp Image 2024-08-18 at 19 27 04_fa19b8e6](https://github.com/user-attachments/assets/670903eb-d758-41f3-ab8b-970706d5583f)
Rank 7

![WhatsApp Image 2024-08-18 at 19 27 04_4de8c959](https://github.com/user-attachments/assets/2f0a795a-544f-4756-8388-c6b16008aee2)
Rank 8

![WhatsApp Image 2024-08-18 at 19 27 04_5f5c0f3c](https://github.com/user-attachments/assets/fe022d54-7b11-413f-890d-58ba17ee06b4)
Rank 9

![WhatsApp Image 2024-08-18 at 19 27 03_15a272e7](https://github.com/user-attachments/assets/47aadd97-c5a9-4c5f-8bdd-ff58cc161b19)

Rank 10

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/1204498b-5e24-4e98-b7e2-03d4dc103815)
@sanjay-kv done

**Comment by akshithachiluka** [comment]
@sanjay-kv  Here is minee
![Yellow Orange Illustrative Winner Announcement Poster](https://github.com/user-attachments/assets/06f4198f-4876-46cd-8e3c-6469c435e6c2)

**Comment by shreyash3087** [comment]
@sanjay-kv 

![Screenshot (528)](https://github.com/user-attachments/assets/5ea312a3-3ed6-43be-a9fe-8476a925fe08)

**Comment by Saumili** [comment]
![Copy of GSSOCxGitHubxPostman (4)](https://github.com/user-attachments/assets/6a799cda-6c04-4a5f-b021-e5dc3f01e91a)
Here's my draft

**Comment by aslams2020** [comment]
Hey @sanjay-kv 
Here are mine - 

### Poster 1 :

![Top10 Poster - Aslam](https://github.com/user-attachments/assets/d7483e5b-cdf8-42ec-b362-e76cbde0130a)


### Poster 2 : 

![GSSoC’24 Winners (1)](https://github.com/user-attachments/assets/7abfa335-bd5c-46ae-bde9-d5587211f4d0)

**Comment by Tejashri-Taral** [comment]
Hey @sanjay-kv ,
Here's mine-

![Top contributors](https://github.com/user-attachments/assets/9bb97b41-9b4f-4aa7-a9b7-3f725da4bf30)

**Comment by suhanipaliwal** [comment]
![Congratulatulations](https://github.com/user-attachments/assets/b73dd328-d673-4da1-a479-2ff1eb76ea52)
![Congratulatulations (1)](https://github.com/user-attachments/assets/e70cadba-c549-40d6-b854-e8ae079ead79)

**Comment by sanjay-kv** [comment]
completed
