### ISSUE TITLE
Task 24: Top 10 PA Poster

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#81]

**Comment by aditya-bhaumik** [comment]
Here is the top 10 pa list in order 

anishka gupta
![WhatsApp Image 2024-08-18 at 19 51 45_70f536c0](https://github.com/user-attachments/assets/5aab295f-6e87-4c7f-ad8c-a899cfc38f3c)

rishi mondal
![WhatsApp Image 2024-08-18 at 19 53 05_f93ec7d4](https://github.com/user-attachments/assets/d2d634a5-02c6-4ffd-80ac-fe0404fb984d)

abhishek sharma
![WhatsApp Image 2024-08-18 at 19 53 34_b104d66a](https://github.com/user-attachments/assets/8a12b13b-3d7b-43ed-b0d1-66946d62128d)

Anurag Verma
![WhatsApp Image 2024-08-18 at 19 55 38_0439d088](https://github.com/user-attachments/assets/2a561873-614a-4776-9040-f1ba8181bf10)

sourabh kumar
![WhatsApp Image 2024-08-18 at 19 56 09_5f5536b6](https://github.com/user-attachments/assets/e3597c58-4308-486f-b2a1-00beb8846784)

vivek prajapati
![WhatsApp Image 2024-08-18 at 19 57 23_dd0342b2](https://github.com/user-attachments/assets/0e7109c1-c08c-4a49-babd-76f3ff54c484)

sanu kumar
![WhatsApp Image 2024-08-18 at 19 57 55_e36271e7](https://github.com/user-attachments/assets/e37c9da1-137f-4f8e-896c-5330e65f67eb)

vaibhav arora
![WhatsApp Image 2024-08-18 at 19 58 33_baaaa651](https://github.com/user-attachments/assets/5049d226-97f1-4cfc-ab7f-478689136ccb)

Himanshu Narware
![WhatsApp Image 2024-08-18 at 19 59 16_090facf8](https://github.com/user-attachments/assets/b7b9a577-9cb0-45b8-9337-71ce2c4ff9c8)

pooranjoy bhattacharya

![WhatsApp Image 2024-08-18 at 19 59 55_b0d57caf](https://github.com/user-attachments/assets/37f6a3a0-ab5e-49bb-b766-ace3c6cb00e8)

@sanjay-kv vivek helped me find this images please add him also for this task

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/97d0ddf2-39bd-407b-9a94-9df3f7f4ac69)
done

**Comment by akshithachiluka** [comment]
![image](https://github.com/user-attachments/assets/c8f5b0bf-da70-4da4-819f-f614a04f7615)
These are top 10 you have selected the wrong numbers please verify

**Comment by akshithachiluka** [comment]
@sanjay-kv  done with my poster 
![TOP 10 PA S](https://github.com/user-attachments/assets/76b4d59c-2ece-4d56-8ac1-7d8ebbf7093c)

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/ce0c8eac-3937-40b1-baf7-eff7e3cf77ee)
@akshithachiluka you are seeing the wrong list

**Comment by vivekv2810** [comment]
As  @aditya-bhaumik mentioned

![image](https://github.com/user-attachments/assets/5e15605b-0d17-451b-bde3-45fd3d00504a)

**Comment by aditya-bhaumik** [comment]
@akshithachiluka which list did you check??

**Comment by akshithachiluka** [comment]
Yeah I have made the changes 
@sanjay-kv here is the final poster


![TOP 10 pa's Poster](https://github.com/user-attachments/assets/410c95b8-b461-4a0c-adb4-5910f3a57867)

**Comment by Saumili** [comment]
Here's my draft, if I need to add any sponsor's logo, let me know.
![Copy of GSSOCxGitHubxPostman (6)](https://github.com/user-attachments/assets/e2c109c6-8593-4213-83d8-c7e9cd5e8db5)

**Comment by aslams2020** [comment]
Hey @sanjay-kv 
here is my design - **Top 10 Project Admins**

![Top10 PA GSSoC’24 Winners](https://github.com/user-attachments/assets/b96521e5-e50c-4608-bf24-1ac53a32c938)

**Comment by Tejashri-Taral** [comment]
Hey @sanjay-kv ,
here is my design - Top 10 Project Admins
![Top PA](https://github.com/user-attachments/assets/549dba6b-ea4a-481d-a734-151e0d37164f)

**Comment by suhanipaliwal** [comment]
![PA TOP 10](https://github.com/user-attachments/assets/ebbd2b56-c667-4752-9eca-7a90c6465ca8)

**Comment by shreyash3087** [comment]
@sanjay-kv 
![Screenshot (535)](https://github.com/user-attachments/assets/68e99c20-80bb-4618-b451-4d87fb755941)

**Comment by vansh-codes** [comment]
Here's my design @sanjay-kv 

![Top 10 PAs](https://github.com/user-attachments/assets/188f4011-9f04-4fa2-bd32-c4ab048800d8)

**Comment by Meetjain1** [comment]
![Copy of Copy of Brown Illustration Hiring Instagram Post (1)](https://github.com/user-attachments/assets/12cf26ba-f93c-4ddb-9408-174910c49f49)

**Comment by MastanSayyad** [comment]
@sanjay-kv Here is my design:

![Top 10 PA](https://github.com/user-attachments/assets/a5015051-7c9d-4fec-a81f-5420bc5de05c)

**Comment by sanjay-kv** [comment]
completed
