### ISSUE TITLE
Task 25: Top 10 Mentor Poster

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#82]

**Comment by aditya-bhaumik** [comment]
Anyone who is searching 

here are the top 10 mentors 

Aman Raj
Prince Pal
Jessica Chawla
Deeepesh Gupta
Ashish Ujjwal
Nihal Rajpal
Vamshi Maskuri
Ayush Tripathi
Neyati

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/993e426a-77d0-45b0-8ff5-af904cbe1544)
@sanjay-kv done

**Comment by akshithachiluka** [comment]
> Anyone who is searching
> 
> here are the top 10 mentors
> 
> Aman Raj ![WhatsApp Image 2024-08-18 at 19 33 39_c130013e](https://private-user-images.githubusercontent.com/92214013/358913177-505e12ce-fdc1-4178-9e44-9ffe64577baa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTMxNzctNTA1ZTEyY2UtZmRjMS00MTc4LTllNDQtOWZmZTY0NTc3YmFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhN2UwYWY5ZGUzMjNkYTM1ZjViYTgyYjdkNTU4NGRjYTc4NDU4M2I0MDg5NjI1NjJlOGJkYTFiNmI1ZTA1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TedtsuXAewu3E_nTFpQXY2X35NsdnAGLShU39pwNLIg)
> 
> Prince Pal ![WhatsApp Image 2024-08-18 at 19 46 16_93f347e7](https://private-user-images.githubusercontent.com/92214013/358913197-1ce8f8cc-9320-4d3d-b2ce-e759ac794299.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTMxOTctMWNlOGY4Y2MtOTMyMC00ZDNkLWIyY2UtZTc1OWFjNzk0Mjk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhM2Q3Njk4NGIwNzk4ZjA0MTM0ODgyOWI1MjkxNTNlODdhODEzMTRmZmRlMmY1NjYxMDc2ZGIyYTllYzA5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pyqJ4uNXTw_iYGc7iiCUOwjCUVE74_F_7o2Umw2eA08)
> 
> Jessica Chawla
> 
> ![WhatsApp Image 2024-08-18 at 19 46 57_b2fad673](https://private-user-images.githubusercontent.com/92214013/358913210-e6b55ad1-6fb8-4bb5-992b-a1747948677a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTMyMTAtZTZiNTVhZDEtNmZiOC00YmI1LTk5MmItYTE3NDc5NDg2NzdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTNkMzc2MGIxM2YzNTIwZGRlODRjYzc2MzJiNTgwNjM1ZDdhMTdkNjVmNTY5NmE3NGFhOTkzMDViYWJlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndJri5MlqESo2H9r4U5mOuLSzb_cWbTnuC2arHo6hCc)
> 
> Deeepesh Gupta
> 
> ![WhatsApp Image 2024-08-18 at 19 36 43_194677c8](https://private-user-images.githubusercontent.com/92214013/358913430-84d0c0de-e6e2-457b-9ca6-6c2547991242.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTM0MzAtODRkMGMwZGUtZTZlMi00NTdiLTljYTYtNmMyNTQ3OTkxMjQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MjRhOWMyNzZkNDI3ZTYyZTBjN2U1OTc4NTY4MmU4NDQ5MzRjNzQ5ODdiMmI3OWI0NGEzNTc4NTczYmM0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oiw9XsksRuFHmWrV3ll7eWwaIts93XBgGxDm4ZbUxMQ)
> 
> Ashish Ujjwal
> 
> ![WhatsApp Image 2024-08-18 at 19 34 34_f3647de3](https://private-user-images.githubusercontent.com/92214013/358913451-113046e1-e8a1-46af-aa15-31fc2c933bcb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTM0NTEtMTEzMDQ2ZTEtZThhMS00NmFmLWFhMTUtMzFmYzJjOTMzYmNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNjNkNDZmNzhjMmM4MTZjZjY2MzhhOWZkMmUxNDVmMzcyMWRkYzhhMzQyZjkyM2U3Nzk1NTFlZGIyZjkwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aq-5hzmdSnSeIxADU9yMgaaRIJkBIQats_SWApy4n0E)
> 
> Nihal Rajpal
> 
> ![WhatsApp Image 2024-08-18 at 19 47 42_e285239b](https://private-user-images.githubusercontent.com/92214013/358913290-0d8f962b-9965-421b-9fac-8067b21479cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTMyOTAtMGQ4Zjk2MmItOTk2NS00MjFiLTlmYWMtODA2N2IyMTQ3OWNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWM3MTJhMDgxYzlhYWIwNDM0NGZlZWUwMzlkNTIzNzNkMzAxNzExMDFlMTU5MjA4NzY1NzdmYjhhM2UzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.378RbyhrmXqa-FbweDNRyiQDHCeCRWI2a-iKrQsi_QI)
> 
> Vamshi Maskuri ![WhatsApp Image 2024-08-18 at 19 46 55_6a792ae9](https://private-user-images.githubusercontent.com/92214013/358913391-745b478a-e956-4a02-8327-e546400afc4e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTMzOTEtNzQ1YjQ3OGEtZTk1Ni00YTAyLTgzMjctZTU0NjQwMGFmYzRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOGY1NjA5ZjY3MTRiNjNmMzdlZDFlZDZhNGExNzVkMmI4OWRkNzU1ZjI4OTI4MmM1MjE2ZWQxMDc0OTg0NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hkdf_48WLfB565Rk9a-QqsmybHkyb7LA7gnvJPTD78s)
> 
> Ayush Tripathi
> 
> ![WhatsApp Image 2024-08-18 at 19 35 13_5591be10](https://private-user-images.githubusercontent.com/92214013/358913487-4d34b047-659c-4c5c-827a-8f38b2b7fd3e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTM0ODctNGQzNGIwNDctNjU5Yy00YzVjLTgyN2EtOGYzOGIyYjdmZDNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzM1ZTc2NDY5MzQ1YjhlNjlmYzBjMzkzOWY1ZjQ3NzY5OGRkMDQ1MGNhOTRiMTg1NjE3ZTIwMjVmNTQyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XQyQo2u8z-8fMKXjhpQ1UKim27NVINqBUyZHlm2lNdM)
> 
> Neyati
> 
> ![WhatsApp Image 2024-08-18 at 19 48 17_bd844785](https://private-user-images.githubusercontent.com/92214013/358913524-bcb26008-6d17-49af-825c-5e3042cf8ca8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTM1MjQtYmNiMjYwMDgtNmQxNy00OWFmLTgyNWMtNWUzMDQyY2Y4Y2E4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZDExODJmMzI3Y2Y0NWE1ZGE5YTZlZmUxMjQyZjA3MGUzMmI3M2JhMzI2OGUzOTFjNDM2OGVkZTgzODU3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBYZtf-kJh4yRji9k6HE_3Cfn3nb_rOOPg26pjcVWpU)
> 
> Pranav Barthwal ![WhatsApp Image 2024-08-18 at 19 55 05_ce4ed9ec](https://private-user-images.githubusercontent.com/92214013/358913332-671e2b51-ff7c-40e5-8fbd-9bac769eb0de.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTgyNjksIm5iZiI6MTcyMzk5Nzk2OSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MTMzMzItNjcxZTJiNTEtZmY3Yy00MGU1LThmYmQtOWJhYzc2OWViMGRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE2MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YmNkMDc1NjQwY2Q3NGVjN2FkOTE0M2E0Yjc3ZTkzYTAyNWIyYjFiNDg4NjhiM2QxMzhhNjhlY2JiNzk4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoTqYbRWFCoPYuQIxNgHPO-Vq2cNwB5dVH0Fj7KCU_A)
> 
> @sanjay-kv vivek helped me find these images

@aditya-bhaumik  AND @VIVEK thanks for the images

**Comment by akshithachiluka** [comment]
@sanjay-kv  here us my poster
![TOP 10 MENTORS Poster](https://github.com/user-attachments/assets/06b953a1-018d-4048-b724-77ad919d00c4)

**Comment by Saumili** [comment]
Here's my draft @sanjay-kv 
![Copy of GSSOCxGitHubxPostman (7)](https://github.com/user-attachments/assets/43fffaea-fb4b-46c3-a90c-23b20c000d50)

**Comment by nikki-05** [comment]
![Screenshot 2024-08-19 002542](https://github.com/user-attachments/assets/49ed3b32-eac7-46f1-8110-08861032f01f)

**Comment by nikki-05** [comment]
![Screenshot 2024-08-19 002648](https://github.com/user-attachments/assets/ec6cbc4c-176f-43a6-b022-fc6f0ac8745f)
@sanjay-kv done sir

**Comment by aslams2020** [comment]
Hey @sanjay-kv 

Here's the Design for **"Top 10 Project Mentors"** 

![Top10 Mentors](https://github.com/user-attachments/assets/24223a97-af69-42cd-9c25-726ad3f8fc1a)

**Comment by shreyash3087** [comment]
@sanjay-kv 

![Screenshot (536)](https://github.com/user-attachments/assets/da0feb21-3a61-4a7d-a089-f3a336211019)

**Comment by vansh-codes** [comment]
Here's my design @sanjay-kv 

![Top 10 PM](https://github.com/user-attachments/assets/916ca7e3-8616-4774-a3ca-47006ff2127d)

**Comment by suhanipaliwal** [comment]
![top 10 mentors](https://github.com/user-attachments/assets/e1bab03d-ba53-4bb1-adcd-144e3429fc38)

**Comment by MastanSayyad** [comment]
@sanjay-kv My design:

![Top 10 Mentors](https://github.com/user-attachments/assets/df6e97c5-bf9d-4a9e-8f44-93ba2c71f578)

**Comment by Meetjain1** [comment]
![Copy of Copy of Brown Illustration Hiring Instagram Post](https://github.com/user-attachments/assets/2da5e343-6ceb-4f8f-9b33-9d744f078d59)

**Comment by sanjay-kv** [comment]
Completed
