### ISSUE TITLE
Task 26: Postman certification feedback poster #1

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#83]
### Discussed in https://github.com/GSSoC24/.github/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **Meetjain1** August 17, 2024</sup>
Here are some ideas that I think can increase the certifications 

1. **Success Stories:** We can include Include top LinkedIn posts from these 900 certified students to add an impact among them.

3. **Certification Challenge:** We can Launch a challenge where students who complete the certification within a set deadline receive both the GSSoC participation certificate and the Postman certification. Additionally, offer a raffle for Postman swags.

4. **Email Marketing:** We can Send targeted emails to students below 500 points on the GSSoC leaderboard and those not on the leaderboard, encouraging them to complete the certification and highlighting its benefits.

5. **Campus Ambassador Support:** We can Re-engage GSSoC campus ambassadors if possible to assist in promoting and guiding students through the Postman certification process.</div>

**Comment by sanjay-kv** [comment]
We can launch success stories by refering to the feedback , 

may be in single poster we can add multiple feedbacks
You can get the feedback from here: https://github.com/GSSoC24/Postman-Challenge/blob/main/add-your-certificate.md


2. Certification challenge is good we can retarget the people on leaderboard who has not take postman certification. @Hemu21 can you help here. 

3. We can provide them Participation certificate: a poster on get your certificate appreciation just by completing postman challenge. 

@Meetjain1  can you list few advantage of and highiglight of getting postman certification?

**Comment by Meetjain1** [comment]
> We can launch success stories by refering to the feedback ,
> 
> may be in single poster we can add multiple feedbacks You can get the feedback from here: https://github.com/GSSoC24/Postman-Challenge/blob/main/add-your-certificate.md
> 
> 2. Certification challenge is good we can retarget the people on leaderboard who has not take postman certification. @Hemu21 can you help here.
> 3. We can provide them Participation certificate: a poster on get your certificate appreciation just by completing postman challenge.
> 
> @Meetjain1 can you list few advantage of and highiglight of getting postman certification?

Sure sir in a while

**Comment by Hemu21** [comment]
Here I am providing the link spreadsheet based on the current leaderboard data. List of all contributors who not completed the postman certificate [Click Here](https://docs.google.com/spreadsheets/d/1cPDmY-y0qX7ylGdcKvoAYKInnkP7AY72dlUJo4MzM7E/edit?usp=sharing)

**Comment by sanjay-kv** [comment]
> Here I am providing the link spreadsheet based on the current leaderboard data. List of all contributors who not completed the postman certificate [Click Here](https://docs.google.com/spreadsheets/d/1cPDmY-y0qX7ylGdcKvoAYKInnkP7AY72dlUJo4MzM7E/edit?usp=sharing)

is there any way that we can match to the existing database and match with email

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/d2c85a29-ef37-4fbf-94ba-f75e05408968)
@sanjay-kv is this good for the success stories

**Comment by Meetjain1** [comment]
> can you list few advantage of and highiglight of getting postman certification?

@sanjay-kv sir,

### Advantages of Postman Student Expert Certification

1. **Enhanced API Skills**:
   - The certification helps students master API fundamentals, including making requests, understanding responses, and using Postman to interact with APIs effectively.

2. **Industry Recognition**:
   - Being certified as a Postman Student Expert is a recognized achievement that showcases your proficiency in API testing and development, which is highly valued in the tech industry.

3. **Career Opportunities**:
   - The certification can make your resume stand out to potential employers, opening doors to internships, job opportunities, and freelance projects in software development, especially in roles involving APIs.

4. **Confidence in API Development**:
   - The hands-on experience gained through the certification process boosts confidence in working with APIs, which is an essential skill in modern software development.

5. **Community and Networking**:
   - Certified students can join the Postman community, connecting with other professionals, sharing knowledge, and participating in Postman events and webinars.

6. **Project Development**:
   - The skills learned can be applied to personal or academic projects, making them more robust, scalable, and efficient through effective API integration.

### Highlights of Postman Student Expert Certification

- **Comprehensive Learning**:
  - The certification program covers a wide range of topics, from basic API concepts to more advanced features like automation and testing, providing a thorough understanding of API lifecycle management.

- **Practical Experience**:
  - The certification includes practical exercises and real-world scenarios, ensuring that students gain hands-on experience with API requests, collections, environments, and more.

- **Interactive Learning Platform**:
  - Postman provides an interactive and user-friendly platform that makes learning enjoyable and accessible, even for those new to APIs.

- **Certification Credential**:
  - Upon completion, students receive an official Postman Student Expert certificate, which can be shared on professional platforms like LinkedIn and included in their portfolio.

**Comment by Saumili** [comment]
Let me know if I can help with design or anything

**Comment by shreyash3087** [comment]
@sanjay-kv maybe something like this -


![Contributor Feedback](https://github.com/user-attachments/assets/b4c4825f-2055-46b3-8c3a-cb865d3b7ba1)

**Comment by sanjay-kv** [comment]
> @sanjay-kv maybe something like this -
> 
> ![Contributor Feedback](https://private-user-images.githubusercontent.com/72603662/358941619-b4c4825f-2055-46b3-8c3a-cb865d3b7ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjQzOTIsIm5iZiI6MTcyNDAyNDA5MiwicGF0aCI6Ii83MjYwMzY2Mi8zNTg5NDE2MTktYjRjNDgyNWYtMjA1NS00NmIzLThjM2EtY2I4NjVkM2I3YmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDIzMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzA2MThmYjU2MzZiMjRhNTdjYzVmYzE0NWViZWYxOWFmMDdkODY3MDc3MDAzMGVhODA2MzQ2NThhZTIzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hHiYF4DYLwOXlVXUvJQAVeQp3KQXiu_cCnAlN74ULuQ)

https://gssoc24.github.io/Postman-Challenge/

can you replace the goodies picture from the one i provided.

**Comment by shreyash3087** [comment]
@sanjay-kv 
![Contributors Feedback](https://github.com/user-attachments/assets/45906c8b-78da-4947-b57d-b34279d15158)

**Comment by sanjay-kv** [comment]
@shreyash3087 this is just awesome, can we make 5 more with different users using the same feedback from provided.

**Comment by sanjay-kv** [comment]
> ![image](https://private-user-images.githubusercontent.com/92214013/358924873-d2c85a29-ef37-4fbf-94ba-f75e05408968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzgzODEsIm5iZiI6MTcyNDAzODA4MSwicGF0aCI6Ii85MjIxNDAxMy8zNTg5MjQ4NzMtZDJjODVhMjktZWYzNy00ZmJmLTk0YmEtZjc1ZTA1NDA4OTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAzMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzlkMmFiOGE2OGRmZWNkNzdlNjJiMGI3ODRiYmVhNzEwMDg5NTgwM2Y5NDU1Zjc4NGY3ZTU2OTA3MjEwZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ehI2aNSzTEoQNzcgolre0kxaYNOLcF_b0Lyz3WkaCo) @sanjay-kv is this good for the success stories

![image](https://github.com/user-attachments/assets/fa2b19ed-404e-4bde-9376-8389638ad33b)
scheduled it for today

**Comment by sanjay-kv** [comment]
> @sanjay-kv ![Contributors Feedback](https://private-user-images.githubusercontent.com/72603662/358945126-45906c8b-78da-4947-b57d-b34279d15158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzgyNTgsIm5iZiI6MTcyNDAzNzk1OCwicGF0aCI6Ii83MjYwMzY2Mi8zNTg5NDUxMjYtNDU5MDZjOGItNzhkYS00OTQ3LWI1N2QtYjM0Mjc5ZDE1MTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAzMjU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NTZjMzAwZjBlMDgxZTNiMTEzODQ2YmE0ZGFmN2RjYjU3NjE3MGFlZmExZTM5NjgyZDNmZDRhNjM0MTcyM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0yQre1ScZ1RrsTAMNDj_xrzjs884cennsSEIBj3fxg)
> 
> Canva LInk - https://www.canva.com/design/DAGOPsIzMJg/bI6XU2bTaUyTCzAZo4PjSg/edit?utm_content=DAGOPsIzMJg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

![image](https://github.com/user-attachments/assets/5bf1915e-9e75-4fec-9015-5f64230eb60f)
 scheduled it for today

**Comment by shreyash3087** [comment]
@sanjay-kv  Done with all the 5 pages - 

![1](https://github.com/user-attachments/assets/542c9c2d-628e-43c5-bce5-c3ce3c9dcc7f)
![2](https://github.com/user-attachments/assets/e9974e7c-efc3-40c5-b6da-867afe122a94)
![3](https://github.com/user-attachments/assets/a3e161d2-6af6-4f2a-b571-3b9e4acb9e1f)
![4](https://github.com/user-attachments/assets/88b4c754-ec2a-4a1b-aa88-569e6b5a41e6)
![5](https://github.com/user-attachments/assets/729f75c9-20b3-4ae6-8888-fbbd12782d67)

**Comment by suhanipaliwal** [comment]
![A good learning experience and practice to understand api and how to use postman -Aditya Sonkusare](https://github.com/user-attachments/assets/6cdf5159-ce25-46ec-b026-9e35d5b1e01a)

**Comment by sanjay-kv** [comment]
> ![A good learning experience and practice to understand api and how to use postman -Aditya Sonkusare](https://private-user-images.githubusercontent.com/161575955/359239593-6cdf5159-ce25-46ec-b026-9e35d5b1e01a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODkzMjUsIm5iZiI6MTcyNDM4OTAyNSwicGF0aCI6Ii8xNjE1NzU5NTUvMzU5MjM5NTkzLTZjZGY1MTU5LWNlMjUtNDZlYy1iMDI2LTllMzVkNWIxZTAxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNDU3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2MxMDQxOTUwMGFlYTlhZTYzNTE5OGVlOGUyMWFkNWQyOGRkYTFkYWU3YWQyMWQ2NzM2ZWZjYTVmODBhYTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jdSbNS8nUSgTxlzjATtFQVbVr4a7RIYqF8tXW1MOfl8)

can you share the canva template link over here,

**Comment by suhanipaliwal** [comment]
https://www.canva.com/design/DAGOUiDhctw/KU0A31xcBDzoTcFWpV6ayQ/edit?utm_content=DAGOUiDhctw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by sanjay-kv** [comment]
completed
