### ISSUE TITLE
Task 27: Suggestion for Re-engaging Postman Certification Participants

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#84]
### Discussed in https://github.com/GSSoC24/.github/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **MastanSayyad** August 17, 2024</sup>
Hi @sanjay-kv 

Since **GSSoC** has ended and there have been no recent posts about the Postman certification on the GSSoC LinkedIn handle, many contributors/people might think the certification program has concluded. To address this, we could create an updated LinkedIn post to inform everyone that the **Postman API certification** is still live. 

We should highlight that they can still earn their certificates and fill out the form to be eligible for swag, including premium Postman goodies.

We can all share, comment and repost it on our LinkedIn profiles to help spread the word and create a new network of engaged participants.

(I might design one if necessary)</div>

**Comment by sanjay-kv** [comment]
@MastanSayyad can you work on the poster part of this mentioned

**Comment by MastanSayyad** [comment]
@sanjay-kv on it 🚀

**Comment by MastanSayyad** [comment]
@sanjay-kv Done

![Postman LIve  Promo](https://github.com/user-attachments/assets/d3dc5086-3207-452f-af08-ba804f427460)
