### ISSUE TITLE
Task 28: 💡 Idea for completing the target

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#85]
### Discussed in https://github.com/GSSoC24/.github/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **Tejashri-Taral** August 17, 2024</sup>
Hey @sanjay-kv ,

for discord users - 
Create polls, quizzes, or short videos related to API development and Postman on social media to keep engagement high and remind participants about the challenge.</div>

**Comment by sanjay-kv** [comment]
@Tejashri-Taral I like the shorts part, can you come up with some create shorts. 

the discord , polls and discussion I don't think it will work anymore.

**Comment by akshithachiluka** [comment]
@sanjay-kv ca i also do the reels or shorts part

**Comment by akshithachiluka** [comment]
@sanjay-kv i made a video 
https://github.com/user-attachments/assets/b02c32ab-e6f5-4660-8b1f-514cae8e545d

**Comment by sanjay-kv** [comment]
> @sanjay-kv can i also do the shorts part 

Sure

**Comment by sanjay-kv** [comment]
This is good. @akshithachiluka can we change the font 
<img width="578" alt="image" src="https://github.com/user-attachments/assets/097a10f5-da3c-4867-932a-5e9a3e514efb">

**Comment by AKSHITHA-CHILUKA** [comment]
Ok @sanjay-kv

**Comment by sanjay-kv** [comment]
@AKSHITHA-CHILUKA let me know whether we can post this today, it would be really great.

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/user-attachments/assets/4d03365b-d3dc-4c86-bc07-4550a9cfa38d
