### ISSUE TITLE
Task 30: Batch 4 Winners Announcment

### ISSUE THREAD

**Issue by sanjay-kv** [GSSoC24/.github#92]
Full Name | (X) Twitter Tweet Link
-- | --
Saumya Srivastava | https://x.com/SaumyaS55749186/status/1825177501381107739
smritip905@gmail.com | https://x.com/nishuu05/status/1825185609318875547
Nitesh Kumar Singh | Na
Saksham Shrivastava | https://x.com/SakshamShr4520/status/1825204316795257184
Abu Bakar | https://x.com/abubakarp789/status/1825217384141173179
Vansh Sardana | https://x.com/sir349/status/1825229989199147162
Ananya Rawat | https://x.com/RrawatAnanya/status/1825225947408371849
Riya | https://x.com/RIYA1427018/status/1825235480683614665?t=H0RHReOnlUv9j6R9JdZk1Q&s=19
Mohammad Ali Yasin | https://x.com/MOHAMMA46823078
Mayuri Ravindra Kolhe | https://x.com/MayuriKolhe10/status/1825395095673201109?t=mTNxVwgLmbhxfJs1InOMgg&s=19
Sharmeen Shaikh | https://x.com/Sharmeen_20
Krishna Kaushik | https://x.com/Krishna24012003/status/1825477490518675585
Het Patel | https://x.com/het_patel004/status/1825520714499461508/
Vrinda Sharma | https://x.com/Vrindashar0107/status/1825634917881098696
Sanu Kumar | https://x.com/sanukumar987147/status/1825873956928369131
Ayush Chaware | https://x.com/ayushchaware8/status/1826014499926642701
Harshal Honde | https://x.com/harshal_honde21/status/1825257573467222253?s=19
Monotosh Mondal | https://x.com/yourmonotosh/status/1826400087565893686?t=MksC2dZ4xg9ttDROW4AlKw&s=19
Ashok Kumar | https://x.com/ashok0p?t=omg9xXQvIQDUAanPRoR41A&s=08
VEMPULURU YASWANTH | https://x.com/Yaswanth9761?t=ihtWug0fd9mEJ_utuqxNLQ&s=09

**Comment by vansh-codes** [comment]
![Congratulations](https://github.com/user-attachments/assets/fb75e90e-85e1-46a1-8e4d-ce9c5f7bf4bc)

**Comment by MastanSayyad** [comment]
@sanjay-kv  **Here is My design:**

![Batch 4 (1)](https://github.com/user-attachments/assets/6fe186fb-afb3-492a-a392-27c5b5258e39)

**Comment by vansh-codes** [comment]
hii @MastanSayyad 
You are really a good designer, my design is nothing in front of yours, just noticed one minute error
- border design is missing in `Sharmeen Shaikh`

![image](https://github.com/user-attachments/assets/0d7a64bb-2cfb-4f1b-a21f-0aa61f2a98ff)

**Comment by MastanSayyad** [comment]
Great Eyesight @vansh-codes ,Thank You!

**Comment by vansh-codes** [comment]
Haha no problem bro! @MastanSayyad

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/10d96a91-5e49-4687-9771-73aba148b05d)

**Comment by shreyash3087** [comment]
![Screenshot (544)](https://github.com/user-attachments/assets/4967493e-c2f3-427a-8243-e1ca11807b8b)

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/14ad7142-e789-40aa-8e47-11ea8410e21f)

**Comment by Meetjain1** [comment]
![Copy of Copy of Copy of Brown Illustration Hiring Instagram Post](https://github.com/user-attachments/assets/c8d73493-9287-493d-bc83-55df9e7f1c30)

**Comment by aditya-bhaumik** [comment]
@vansh-codes  and @Meetjain1 your designs are good just a small update please  remove the mail id of the winner her name is smriti priya you can just edit your comment to change the image

**Comment by vansh-codes** [comment]
Sure @aditya-bhaumik 
Thanks for letting us know!

**Comment by RadhikaMalpani1702** [comment]
![1eadfdb0-aee5-4b4c-9e39-65a0c9af1b7c](https://github.com/user-attachments/assets/90d04db3-2a6a-4960-9526-5b084c70d731)

**Comment by Saumili** [comment]
@sanjay-kv 
![Copy of The Grand Giveaway Bonanza Awaits!](https://github.com/user-attachments/assets/4415e105-092d-4640-835b-a8eebc328bf1)

**Comment by sanjay-kv** [comment]
> ![Congratulations (1)](https://private-user-images.githubusercontent.com/114163734/360443453-47d0f7a1-224c-4a22-bfd3-3290327f5762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODkxMTcsIm5iZiI6MTcyNDM4ODgxNywicGF0aCI6Ii8xMTQxNjM3MzQvMzYwNDQzNDUzLTQ3ZDBmN2ExLTIyNGMtNGEyMi1iZmQzLTMyOTAzMjdmNTc2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNDUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmQyZTMzYTYzZjEzZTZlMWMwYmQ0NGYyZDdjNzgxNDM3MzJmYmI0ZjBhMTgxYTljYzZhYjFjMTdhNDE0ZWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OVzLTCK12CBIijA3BgLWaqdt1scPk7sgWOqExTZdZ24)

can you share the canva link, so next time i wont bother you guys

**Comment by sanjay-kv** [comment]
> @sanjay-kv **Here is My design:**
> 
> ![Batch 4 (3)](https://private-user-images.githubusercontent.com/101971980/360437113-9444955a-d731-470e-93a1-e9f9085f1180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODkxNjIsIm5iZiI6MTcyNDM4ODg2MiwicGF0aCI6Ii8xMDE5NzE5ODAvMzYwNDM3MTEzLTk0NDQ5NTVhLWQ3MzEtNDcwZS05M2ExLWU5ZjkwODVmMTE4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNDU0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGEzZjU5YmYxNzc3MGQ4NjkxNzcxNjI4ZDY5YjNjODUyMjBlOGZmMjMwMWU0ZTRmODE0YWY2ZTRkMDk2MzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DV4ie91cAiFa5M7x9aluGrYwTHSP-1VQpBs3ikfcan8)

can you share the canva template here so next time i wont bother you

**Comment by vansh-codes** [comment]
> > ![Congratulations (1)](https://private-user-images.githubusercontent.com/114163734/360443453-47d0f7a1-224c-4a22-bfd3-3290327f5762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODkxMTcsIm5iZiI6MTcyNDM4ODgxNywicGF0aCI6Ii8xMTQxNjM3MzQvMzYwNDQzNDUzLTQ3ZDBmN2ExLTIyNGMtNGEyMi1iZmQzLTMyOTAzMjdmNTc2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNDUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmQyZTMzYTYzZjEzZTZlMWMwYmQ0NGYyZDdjNzgxNDM3MzJmYmI0ZjBhMTgxYTljYzZhYjFjMTdhNDE0ZWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OVzLTCK12CBIijA3BgLWaqdt1scPk7sgWOqExTZdZ24)
> 
> can you share the canva link, so next time i wont bother you guys


Here it is @sanjay-kv 
https://www.canva.com/design/DAGOlFEpFFQ/7EEjXvvY4iYcnC6Zk3hEjw/edit?utm_content=DAGOlFEpFFQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
